
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topper from "@/Components/Shared/Topper";
import Navbar from "@/Components/Shared/Navbar";
import HomeBanner from "@/Components/Home/HomeBanner";
// import HomeBanner from '@/Components/HomeBanner'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Topper />
        <div className="relative">
          <div className="sticky top-0 z-10">
            <Navbar/>
          </div>
          <div className="">
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
